### ISSUE TITLE
Community Product Development

### ISSUE THREAD

**Issue by Santiago8888** [Santiago8888/Asterix#21]

**Comment by PaolaHH** [comment]
### Purpose/Mission:
    1) Develop a plan to build a successful community 
    2) Define community's business model
    3) Grow the community

### Steps:
1) Define our persona
2) Define our business objective
3) Define MVP 
4) Define community members objective
5) Develop a plan to engage our initial members
6) Atract new memebers

### TO DO:
* [ ] Market research about our persona
* [ ] Quantify business objective with 5 KPI's
* [ ] Define key features and benefits 
* [ ] Get the first 10 members: 5 very engaged
* [ ] Find the best place to start the community
* [ ] Lauch strategy

**Comment by Santiago8888** [comment]
### Persona Definition:

Define the identity of the Community and initial members' common traits.

#### Brainstorn:

- [ ] Startup Founders
- [ ] By Industry
- [ ] By knowledge they seek
- [ ] By City/Location
- [ ] Small Business Owners
- [ ] Intrapeneurs
- [ ] By purpose - high achievers

**TODO:** market research on each area
*HINT:* 3 cold outreaches should be enough.


### Environment Analysis: 

- Porter 5 forces.
**By Product:** Documented methodology of product development for SocialQ. 


#### Other:

- [ ] Find appropriate slang to refer to keywords of the community.
- [ ] Define how the vision will be transmitted, presented, and marketed.
- [ ] Find the most suitable documents to communicate findings during research, e.g. customer interviews, SWOT.

**Comment by Santiago8888** [comment]
### User Persona: 

#### Demographic:
·        Ciudad de México
·        Sexo indistinto
·        Edad: 30 años
·        Industria: múltiple
·        Puesto: puestos con gente a cargo, personas con trayectoria de crecimiento continuo

####  Pschye:
El intrapreneur es aquella persona que no desea salir de la empresa en la que se encuentra para iniciar un nuevo negocio. 
Es alguien capaz de transformar, a través de su visión, **espíritu emprendedor** y creatividad, un producto o servicio, estableciendo una nueva área de negocios dentro de su actual organización.

1.      Se compromete con la empresa:
         Personas que desean crecer junto con la organización
         Identifican necesidades de la empresa *¿Cómo detectarlo?*

2.      Se comporta como un líder:
         Dirige a su equipo
3.      Perseverante
4.      Destaca como empleado
5.      Quiere crecer dentro de la organización
·        Intrapreneurs en empresas internacionales que aun no tienen tanta presencia en México: que tengan mucho contacto con el internacional.
·        Valores: crecimiento personal, liderazgo, autoconocimiento, autocrítica, curiosidad, proactivos, apasionados, optimismo, sentido crítico, seguridad personal, iniciativa.


#### Objectives
Ø Formar parte de una comunidad de personas comprometidas que se ayuden entre ellas
Ø Ayudar a personas que están en una posición en la que desean crecer, apoyarlos a encontrar su potencial y proporcionar herramientas adecuadas.

####  Success Definition
Ø Personas muy comprometidas, de diversas industrias y diversos puestos que se ayudan entre sí
Ø Material de valor, conferencias con personas importantes
Ø Crecimiento orgánico y exponencial
Ø Ser reconocidos como la comunidad de intrapreneurs
**TO DO:** quantify this with KPIs

#### Purpose
Ø The product itself
Ø Product innovation and feedback: developing

**Comment by Santiago8888** [comment]
Find appropriate slang to refer to the keywords of the community.

Name of the community: **Mexico 2040** - Find alternative
Name of the members: **Leaders**
Mission: Develop leadership qualities in the community.

**Comment by Santiago8888** [comment]
#### Brainstorm pre-features:

Problems:
* We have a lack of experience managing a community.
* We want the community to be an ally, not a time-drainer.
* Location, very friendly UI.

Ideas
- [ ] Experiment/test: create a short-lived community, e.g. for the unemployed. [Problem I]
- [ ] Develop the Linkedin Learnings product with the community. [Twitter - InfoProduct - Growth Circle]
- [ ] Design a great onboarding experience, add continuous support.


Tasks:
- [ ] When doing research, please try to learn how communities grew. => design the features.
- [ ] List of features from other communities, with small remarks of strengths and weaknesses.

**Comment by Santiago8888** [comment]
Questions on Launch Strategy:

* How to attract the first leaders? 
* How to invite good leaders?
* How to find make money when starting?


**Idea:** 4-week virtual Workshop to improve LinkedIn Profile & Presence

Hypothesis: An influential LinkedIn presence translates to career growth. 

- Week One: Optimize your Profile: share your experience and accomplishments.
- Week Two: Connect with who you admire.
- Week Three: Be noticed: Learn how to post!
- Week Four: Be an expert, publish an article.

Cost: $299 MXN & $149 for unemployed.


Allies: 
* RH strategic: share profits. - Friend.

TODOs:
- [ ] Consider pros & cons of a pre-launch.
- [ ] Start structuring the course (Santiago)
- [ ] Meditate about how to Market and sell this Workshop (Paola).
